from __future__ import annotations

from typing import Protocol

from .aigc import generate_product_ideas
from .aigc_verifier import verify_product_item
from .config import settings
from .data_loader import load_dataset
from .models import ProductItem, ProductProviderName


class ProductProvider(Protocol):
    name: str

    def search(self, keyword: str, budget: float | None, tags: list[str], limit: int, scenario: str = "shopping") -> list[ProductItem]:
        ...


class LocalProductProvider:
    name = "local-json"

    def search(self, keyword: str, budget: float | None, tags: list[str], limit: int, scenario: str = "shopping") -> list[ProductItem]:
        dataset = load_dataset()
        keyword_terms = [term for term in [keyword, *tags] if term]
        products: list[tuple[float, ProductItem]] = []

        for product in dataset["products"]:
            product_tags = product.get("tags", [])
            text = " ".join([product["name"], product.get("category", ""), *product_tags])
            keyword_score = sum(1 for term in keyword_terms if term in text)
            budget_score = 1.0 if budget is None or product.get("price", 0) <= budget else 0.4
            score = keyword_score + budget_score
            if score <= 0:
                continue
            product_item = ProductItem(
                id=product["id"],
                name=product["name"],
                provider=self.name,
                category=product.get("category"),
                price=product.get("price"),
                tags=product_tags,
                reason="From local sample product data; use only for development fallback.",
                purchase_hint="Replace with an owned catalog or real commerce provider before production.",
                source="sample-data",
            )
            product_item.realness = verify_product_item(product_item)
            products.append((score, product_item))

        return [item for _, item in sorted(products, key=lambda pair: pair[0], reverse=True)[:limit]]


class AigcProductProvider:
    name = "aigc-generated"

    def search(self, keyword: str, budget: float | None, tags: list[str], limit: int, scenario: str = "shopping") -> list[ProductItem]:
        ideas = generate_product_ideas(keyword=keyword, scenario=scenario, budget=budget, tags=tags, limit=limit)
        products: list[ProductItem] = []
        for index, idea in enumerate(ideas, start=1):
            idea_tags = idea.get("tags", [])
            product = ProductItem(
                id=f"aigc-{index:03d}",
                name=str(idea.get("name", f"generated product {index}")),
                provider=self.name,
                category=str(idea.get("category", "generated product")),
                price=float(idea["price"]) if isinstance(idea.get("price"), (int, float)) else None,
                tags=[str(tag) for tag in idea_tags] if isinstance(idea_tags, list) else [],
                reason=str(idea.get("reason", "Generated by AIGC from the current life goal.")),
                purchase_hint=str(idea.get("purchase_hint", "Verify brand, specification, reviews, and price before purchase.")),
                source="aigc",
            )
            product.realness = verify_product_item(product)
            if not product.realness.passed and settings.strict_real_data:
                continue
            if not product.realness.passed:
                product = _downgrade_unsafe_product(product, index)
            products.append(product)
        return products


def get_product_provider(provider: ProductProviderName = "auto") -> ProductProvider:
    if provider in ("auto", "aigc"):
        return AigcProductProvider()
    return LocalProductProvider()


def _downgrade_unsafe_product(product: ProductItem, index: int) -> ProductItem:
    downgraded = ProductItem(
        id=product.id,
        name=f"AIGC product need {index}",
        provider=product.provider,
        category=product.category or "generated product need",
        price=product.price,
        tags=product.tags,
        reason="AIGC generated this as a product category need. Risky commerce claims were removed.",
        purchase_hint="This is a category-level need only. Verify brand, specification, reviews, and final cost independently before buying.",
        source=product.source,
    )
    downgraded.realness = verify_product_item(downgraded)
    return downgraded


def product_provider_status() -> dict[str, dict[str, bool | str]]:
    return {
        "aigc": {
            "configured": bool(settings.llm_api_key),
            "implemented": True,
            "source": "openai-compatible-llm" if settings.llm_api_key else "not-configured",
            "fallback": "disabled" if settings.strict_real_data else "template-generator",
        },
        "local": {
            "configured": not settings.strict_real_data,
            "implemented": True,
            "source": "data/products.json",
            "fallback": "development-only",
        },
    }
